services:
  trace-that-route:
    image: registry.uni-kassel.dev/trace-that-route/server
    build:
      context: .
      dockerfile: Dockerfile
      platforms: [linux/amd64, linux/arm64]
    container_name: trace_that_route
    ports:
      - "8000:8000"
    restart: unless-stopped
